language: go
go:
  - 1.8
  - 1.9
  - tip
services:
  - mysql
  - postgresql
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y unixodbc unixodbc-dev
  - go get github.com/mattn/goveralls github.com/golang/dep
install:
  - ./contrib/grab-oracle.sh
  - export PKG_CONFIG_PATH=$TRAVIS_BUILD_DIR
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/instantclient_12_1
  - $GOPATH/bin/dep ensure
script:
  - go build -tags 'all icu fts5 vtable json1'
  - go test -tags all -v ./stmt
