language: go
go:
  - 1.10.x
  - tip
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get -qq update
  - sudo apt-get install -y unixodbc unixodbc-dev bats expect
  - go get github.com/mattn/goveralls
install:
  - ./contrib/oracle/grab-instantclient.sh $TRAVIS_BUILD_DIR
  - export PKG_CONFIG_PATH=$TRAVIS_BUILD_DIR
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/instantclient_12_1
  - go get -v -u -tags 'all icu fts5 vtable json1' ./...
script:
  - go test ./stmt/
  - go build -tags 'all icu fts5 vtable json1'
  - export USQL_SHOW_HOST_INFORMATION=false
  - bats -t ./contrib/tests.bats
