[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/gohxs/readline"

[[constraint]]
  branch = "master"
  name = "github.com/SAP/go-hdb"
